@url = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJGaWxtZXMgQVBJIiwic3ViIjoiYWRtaW4iLCJleHAiOjE3NzYyODIwMTF9.j3wOBvMJmam-Qhd7c0uPn69v58L-bdoFLzjBse11H-c

POST {{url}}/afericoes
Authorization:  Bearer {{token}}
Content-Type: application/json

{
    "idSensor" : "34",
    "unidade" : "Graus Celsius",
    "valor" : "26"
}

###
GET {{url}}/afericoes
Authorization:  Bearer {{token}}

###
PUT {{url}}/afericoes/1
Authorization:  Bearer {{token}}
Content-Type: application/json

{
    "idSensor" : "34",
    "unidade" : "Graus Celsius",
    "valor" : "30"
}

###
GET {{url}}/afericoes/1
Authorization:  Bearer {{token}}

###
DELETE {{url}}/afericoes/1
Authorization:  Bearer {{token}}